##server:
##  port: 8443
##  ssl:
##    key-store: keystore.p12
##    key-store-password: stay3492
##    keyStoreType: PKCS12
##    keyAlias: stay
##
##frontend:
#  url: http://localhost:3000

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: gM17tjsUhUjbusSsqoli
            clientSecret: aojE3YttTr
            redirectUri: "https://localhost:8443/login/oauth2/code/naver"
            authorizationGrantType: authorization_code
            scope: name,email,birthyear
          kakao:
            client-id: 913ff61f70cf94ef3616d9cadda9cd8c
            clientSecret: bb1daba02afb6f53e4ffceadf2b4d598
            redirect-uri: "https://localhost:8443/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname
          google:
            clientId: 568884105992-g6t1g5a4oeuq5f05be707ehjtb6vomua.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "https://localhost:8443/login/oauth2/code/google"
            authorizationGrantType: authorization_code
            scope: profile,email

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response # 네이버 API가 사용자 정보를 "response" 객체 안에 넣어 반환
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id


  datasource:
    url: jdbc:mysql://localhost:3306/valanse
    username: root
    password: lijrmcp1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      #host: redis
      port: 6379

jwt:
  secret: da69287c68f415506faca9366f7cbc05b39d59406c699da269514ef2f6e3057b564b85d1b5be8f151845c55a3d9d1f912dc657d7d6cb4258c7b777cb8287a092
