spring:

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: shLrTHnjRILnVJD5mN2V
            clientSecret: xS5mKrEnrv
            redirectUri: "http://localhost:8080/login/oauth2/code/naver"
            authorizationGrantType: authorization_code
            scope: name,email,birthyear
          kakao:
            client-id: 3c1e0ee56b5fa05c9eafbe6f6991afba
            clientSecret: 731cbcdf1935dc8a5a32eb9acd52b3b5
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname
          google:
            clientId: 731622068986-gsp4m1gtinl4is47ius9vj06el23nrih.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://localhost:8080/login/oauth2/code/google"
            authorizationGrantType: authorization_code
            scope: profile,email

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response # 네이버 API가 사용자 정보를 "response" 객체 안에 넣어 반환
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id


  datasource:
    url: jdbc:mysql://localhost:3306/valanse
    username: root
    password: lijrmcp1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      #host: redis
      port: 6379

jwt:
  secret: da69287c68f415506faca9366f7cbc05b39d59406c699da269514ef2f6e3057b564b85d1b5be8f151845c55a3d9d1f912dc657d7d6cb4258c7b777cb8287a092








#spring:
#
#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            clientId: shLrTHnjRILnVJD5mN2V
#            clientSecret: xS5mKrEnrv
#            redirectUri: "http://192.168.60.56:8080/login/oauth2/code/naver"
#            authorizationGrantType: authorization_code
#            scope: name,email,birthyear
#          kakao:
#            client-id: 3c1e0ee56b5fa05c9eafbe6f6991afba
#            clientSecret: 731cbcdf1935dc8a5a32eb9acd52b3b5
#            redirect-uri: "http://192.168.60.56:8080/login/oauth2/code/kakao"
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            scope: profile_nickname
#          google:
#            clientId: 731622068986-gsp4m1gtinl4is47ius9vj06el23nrih.apps.googleusercontent.com
#            clientSecret: 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
#            redirectUri: "http://192.168.60.56:8080/login/oauth2/code/google"
#            authorizationGrantType: authorization_code
#            scope: profile,email
#
#        provider:
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response # 네이버 API가 사용자 정보를 "response" 객체 안에 넣어 반환
#          kakao:
#            authorization_uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user_name_attribute: id
#
#  datasource:
#    url: jdbc:mysql://192.168.60.56:3306/valanse
#    username: root
#    password: db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  data:
#    redis:
#      host: 192.168.60.56
#      port: 6379
#
#jwt:
#  secret: da69287c68f415506faca9366f7cbc05b39d59406c699da269514ef2f6e3057b564b85d1b5be8f151845c55a3d9d1f912dc657d7d6cb4258c7b777cb8287a092
